name: wordpress
version: 1.0.5
appVersion: 4.9.5
description: Laboconnect software deployment
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
- wordpress
- cms
- blog
- http
- web
- application
- php
home: http://www.wordpress.com/
sources:
- https://github.com/bitnami/bitnami-docker-wordpress
maintainers:
- name: mbi
  email: matthieu.billiottet@dlsante.fr
engine: gotpl
