name: laboconnect
version: 0.6.8
appVersion: 1.8.3
description: General-purpose web UI for Kubernetes clusters
keywords:
- laboconnect
home: https://github.com/kubernetes/dashboard
sources:
- https://github.com/kubernetes/dashboard
maintainers:
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
