# for kubernetes-dashboard
# This is a YAML-formatted file.
# # Declare name/value pairs to be passed into your templates.
# # name: value

image:
  repository: k8s.gcr.io/kubernetes-dashboard-amd64
  tag: v1.8.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 443

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

ingress:
  enabled: false
  path: ""
rbac:
  create: true
  clusterAdminRole: false
